version: "2.2"
services:
  cloud9:
    restart: always   
    container_name: cloud9
    image: cloud9
    ports:
      - "0.0.0.0:9090:22"
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:8888:8888"
    volumes:
      - wkspace:/home/ubuntu/workspace
      - sshdir:/home/ubuntu/.ssh
    security_opt:
      - seccomp:unconfined

volumes:
 wkspace:
 sshdir:
