version: "2.2"
services:
  cloud9:
    restart: always   
    container_name: cloud9
    image: cloud9
    ports:
      - "0.0.0.0:9090:22"
      - "0.0.0.0:5000:5000"
    volumes:
      - c9home:/home
    security_opt:
      - seccomp:unconfined

volumes:
  c9home:
